language: cpp

os:
  - linux
#  - osx

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo /etc/init.d/postgresql stop; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get remove postgresql-9.* -y; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get update -q; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get upgrade --allow-unauthenticated -y; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install g++-7 -y; fi
  - wget http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2
  - tar -jxf boost_1_64_0.tar.bz2
  - sudo cp -r boost_1_64_0/boost /usr/local/include

install:
  - g++ -v
  - cd $TRAVIS_BUILD_DIR/examples
  - for it in $(ls); do cd $it && qmake; cd ..; done

script:
  - cd $TRAVIS_BUILD_DIR/examples
  - for it in $(ls); do cd $it && make; cd ..; done
